// Generated by Ignite ignite.com/cli

import type { StdFee } from "@cosmjs/launchpad";
import type { EncodeObject, GeneratedType, OfflineSigner } from "@cosmjs/proto-signing";
import { Registry } from "@cosmjs/proto-signing";
import type { DeliverTxResponse } from "@cosmjs/stargate";
import { SigningStargateClient } from "@cosmjs/stargate";

import type { IgniteClient } from "../client";
import { msgTypes } from "./registry";
import { Api } from "./rest";
import { SigningInfo as typeSigningInfo } from "./types";
import { ValidatorMissedBlocks as typeValidatorMissedBlocks } from "./types";
import { MissedBlock as typeMissedBlock } from "./types";
import { ValidatorSigningInfo as typeValidatorSigningInfo } from "./types";
import { Params as typeParams } from "./types";
import { MsgUnjail } from "./types/cosmos/slashing/v1beta1/tx";

export { MsgUnjail };

export interface sendMsgUnjailParams {
  value: MsgUnjail;
  fee?: StdFee;
  memo?: string;
}

export interface msgUnjailParams {
  value: MsgUnjail;
}

export const registry = new Registry(msgTypes);

export interface Field {
  name: string;
  type: unknown;
}

export const getStructure = (template) => {
  const structure: { fields: Field[] } = { fields: [] };
  for (const [key, value] of Object.entries(template)) {
    const field = { name: key, type: typeof value };
    structure.fields.push(field);
  }
  return structure;
};

export const defaultFee = {
  amount: [],
  gas: "200000",
};

export interface TxClientOptions {
  addr: string;
  prefix: string;
  signer?: OfflineSigner;
}

export const txClient = (
  { signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" },
) => {
  return {
    async sendMsgUnjail({ value, fee, memo }: sendMsgUnjailParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error("TxClient:sendMsgUnjail: Unable to sign Tx. Signer is not present.");
      }
      try {
        const { address } = (await signer.getAccounts())[0];
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, {
          registry,
        });
        const msg = this.msgUnjail({ value: MsgUnjail.fromPartial(value) });
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
      } catch (e: any) {
        throw new Error(`TxClient:sendMsgUnjail: Could not broadcast Tx: ${e.message}`);
      }
    },

    msgUnjail: ({ value }: msgUnjailParams): EncodeObject => {
      try {
        return { typeUrl: "/cosmos.slashing.v1beta1.MsgUnjail", value: MsgUnjail.fromPartial(value) };
      } catch (e: any) {
        throw new Error(`TxClient:MsgUnjail: Could not create message: ${e.message}`);
      }
    },
  };
};

export interface QueryClientOptions {
  addr: string;
}

export const queryClient = ({ addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

export class SDKModule {
  public query: ReturnType<typeof queryClient>;
  public tx: ReturnType<typeof txClient>;
  public structure: Record<string, unknown>;
  public registry: [string, GeneratedType][] = [];

  constructor(client: IgniteClient) {
    this.query = queryClient({ addr: client.env.apiURL });
    this.updateTX(client);
    this.structure = {
      SigningInfo: getStructure(typeSigningInfo.fromPartial({})),
      ValidatorMissedBlocks: getStructure(typeValidatorMissedBlocks.fromPartial({})),
      MissedBlock: getStructure(typeMissedBlock.fromPartial({})),
      ValidatorSigningInfo: getStructure(typeValidatorSigningInfo.fromPartial({})),
      Params: getStructure(typeParams.fromPartial({})),
    };
    client.on("signer-changed", (signer) => {
      this.updateTX(client);
    });
  }
  updateTX(client: IgniteClient) {
    const methods = txClient({
      signer: client.signer,
      addr: client.env.rpcURL,
      prefix: client.env.prefix ?? "cosmos",
    });

    this.tx = methods;
    for (const m in methods) {
      this.tx[m] = methods[m].bind(this.tx);
    }
  }
}

export const Module = (test: IgniteClient) => {
  return {
    module: {
      CosmosSlashingV1Beta1: new SDKModule(test),
    },
    registry: msgTypes,
  };
};

export default Module;
